version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/"
    assignees:
      - "MoeDevelops"
    schedule:
      interval: "weekly"
      timezone: "Europe/Berlin"
      day: "friday"
      time: "12:00"
    open-pull-requests-limit: 20
  - package-ecosystem: "github-actions"
    directory: "/"
    assignees:
      - "MoeDevelops"
    schedule:
      interval: "weekly"
      timezone: "Europe/Berlin"
      day: "friday"
      time: "12:00"
